sudo: true
language: scala
services:
  - docker
scala:
  - 2.12.7
  - 2.11.12

jdk:
  - oraclejdk8

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "ChristopherDavenport/testcontainers-specs2" && sbt ++$TRAVIS_SCALA_VERSION publish
